### ISSUE TITLE
windsensorserver.py actual_windspeed_msec

### ISSUE THREAD

**Issue by marram445** [siro20/windsensor#1]
hi,
Thanks for the greate software!
the variable actual_windspeed_msec is not a global variable. Hence the tcpConnectionHandler delivers constantly 0. 

I added a function:
def actual():
        return actual_windspeed_msec
and changed the line in the windsensorserver.py to
 self.request.sendall('{"windspeed": %f, "time": "%s"}' % (actual(),time.strftime('%X %x %Z')))

Moreover i added in 
threadeval():
the line global actual_windspeed_msec

**Comment by siro20** [comment]
You are right, i'll send a fix.
